TASK-2.17 main page layout
htmlacademy-htmlcss/1565521-technomart-29 pull request #2
Opened 2020-09-13 13:12 UTC by andmitri

2020-09-14 07:05 UTC, nikkypizza requested changes

2020-09-14 07:05 UTC, nikkypizza commented on index.html
> +        <a href="mail@htmlacademy.ru">mail@htmlacademy.ru</a>
[Как сделать ссылку на адрес электронной почты](https://webref.ru/recipe/2328)

2020-09-14 07:05 UTC, nikkypizza commented on index.html
> +        +7 (812) 555-05-55
Можно обернуть в `address` и выделить телефон ссылкой

2020-09-15 10:50 UTC, nikkypizza commented on index.html
> +        <li><button type="button">Кредит</button></li>
В макете также есть два скрытых слоя с остальными вкладками, по ТЗ они тоже должны быть сверстаны
![image](https://user-images.githubusercontent.com/30810655/93201771-50076280-f75a-11ea-8e06-01f9e048a9a9.png)

2020-09-15 17:30 UTC, andmitri commented on blank.html
> +Not implemented
Удалила, см f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:31 UTC, andmitri commented on index.html
> +      <section>
Убрала лишние секции. f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:32 UTC, andmitri commented on index.html
> +      </section>
Обернула в nav, убрала section. f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:33 UTC, andmitri commented on index.html
> +      <p>г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</p>
Добавила address для адресов на странице. f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:33 UTC, andmitri commented on index.html
> +  </header>
Сгруппировала объекты по трем блокам.f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:40 UTC, andmitri commented on index.html
> +    </section>
Я попыталась реализовать слайдер с помощью кнопок и радиобаттонов (то, что у нас было по программе). Мне кажется, что это не самый лучший солюшен. Загуглила как еще можно сделать карусель - с помощью джаваскрипта. Но я так понимаю, на этом уровне этого пока делать не нужно? f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:40 UTC, andmitri commented on index.html
> +      <a href="blank.html">все популярные товары</a>
Добавила ссылку в блок с загловком. f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:42 UTC, andmitri commented on index.html
> +            <img src="img/product-2.jpg" width="184" height="164" alt="Перфоратор BOSCH BFG 3000">
Да, я совершенно согласна, что назвать изображения нужно по другому. Когда буду работать с изображениями назову их по-человечески.

2020-09-15 17:43 UTC, andmitri commented on index.html
> +      <p>Интернет-магазин <br> строительных материалов <br>и инструментов для ремонта</p>
Убрала все <br>f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:43 UTC, andmitri commented on index.html
> +            <p>25500 Р.</p>
Обернула в del и ins f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:43 UTC, andmitri commented on index.html
> +      <a href="blank.html">все производители</a>
Добавила ссылку в блок с заголовком. f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:52 UTC, andmitri commented on index.html
> +        <li hidden>
Убрала hidden f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 17:59 UTC, andmitri commented on index.html
> +        </li>
Сделала иконки f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 18:00 UTC, andmitri commented on index.html
> +        <a href="mail@htmlacademy.ru">mail@htmlacademy.ru</a>
Сделала ссылку н адрес электронном почты f96777d3a2b29801e3150b320d7a9035b8b75ce3

2020-09-15 18:05 UTC, andmitri commented on index.html
> +  <footer>
Сгруппировала в три блока 225900a4b3667b2d80f4b33bcac10caaedce6a6b

2020-09-15 18:08 UTC, andmitri commented on index.html
> +        <li><button type="button">Кредит</button></li>
Добавила недостающие вкладки.
Переделала кнопки на радиобаттоны, поставила для радиобаттона доставки атрибут checked. 225900a4b3667b2d80f4b33bcac10caaedce6a6b

2020-09-16 08:48 UTC, nikkypizza requested changes
Молодец, ты проделала хорошую работу над ошибками)

Оставил пару комментариев, поправь к следующему заданию. В будущем еще придется править верстку, когда будем стилизовать, но на сейчас все ок

2020-09-16 08:48 UTC, nikkypizza commented on index.html
> +    <ul>
Списки нужны для перечисления элементов связанных по смыслу пр. - список товаров, список книг, оглавление.  Тут же элементы между собой не связаны по смыслу, использовать список избыточно, обычного блочного контейнера вроде `div` достаточно.

2020-09-16 08:48 UTC, nikkypizza commented on index.html
> +          <form action="https://echo.htmlacademy.ru/courses" method="post">
- Формы тут не нужны, мы данные не отправляем.
- Чтобы радио кнопки вели себя как нужно, у них должен быть одинаковый атрибут `name`. [Референс](https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/radio)
- Кнопки слайдера и радиокнопки общие для всего слайдера. 
Т.е. структура такая: Слайдер > два чекбокса, две кнопки и список слайдов,

2020-09-16 08:48 UTC, nikkypizza commented on index.html
>            <h3>ПЕРФОРАТОРЫ</h3>
Весь слайдер ПЕРФОРАТОРЫ является четвертым пунктом списка услуг
![image](https://user-images.githubusercontent.com/30810655/93310790-e3e63680-f80d-11ea-85c8-112a44bf47ba.png)

2020-09-16 08:48 UTC, nikkypizza commented on index.html
> +      <p><a href="">все производители</a></p>
Тут нужно объединить в один блок, можно в `header` или `div`
```suggestion 
  <header>
      <h2>популярные производители:</h2>
      <a href="">все производители</a>
   </header>
```

2020-09-16 08:48 UTC, nikkypizza commented on index.html
> +      <form action="https://echo.htmlacademy.ru/courses" method="post">
Тут форма так же не требуется

2020-09-16 08:48 UTC, nikkypizza commented on index.html
>      <section>
Не хватает `mailto` на ссылке с почтой

2020-09-16 08:48 UTC, nikkypizza commented on index.html
> +  </header>
Уже гораздо лучше, но когда будем делать сетки придется добавить еще оберток тут и в подвале

2020-09-16 08:48 UTC, merged

2020-09-19 14:06 UTC, andmitri commented on index.html
>            <h3>ПЕРФОРАТОРЫ</h3>
Мы обсуждали этот момент на лекции, лектор сказал, что можно вынести слайдер в отдельный блок. Так как по смыслу он не очень хорошо вписывается в список услуг. Я это понимаю так: в слайдере находятся актуальные объявления, сезонные предложения, скидки.

2020-09-19 14:34 UTC, andmitri commented on index.html
> +    <ul>
Заменила на div 0c54abe22709bd5fbe38c09380a23675117d15ee

2020-09-19 14:38 UTC, andmitri commented on index.html
> +          <form action="https://echo.htmlacademy.ru/courses" method="post">
Убрала формы, 
поменяла на одинаковые имена
сделала кнопки и радиокнопки общими для всего слайдера.

2020-09-19 14:39 UTC, andmitri commented on index.html
> +      <form action="https://echo.htmlacademy.ru/courses" method="post">
Убрала форму.

2020-09-19 14:39 UTC, andmitri commented on index.html
>      <section>
Добавила mailto.