TASK-3.15 main page stylization
htmlacademy-htmlcss/1565521-technomart-29 pull request #3
Opened 2020-09-21 10:57 UTC by andmitri

2020-09-21 19:19 UTC, nikkypizza requested changes

2020-09-21 19:19 UTC, nikkypizza commented on css/style.css
> +.button{
По макету текст в `красных кнопках` написан капсом

2020-09-21 19:19 UTC, nikkypizza commented on index.html
> +      <iframe class="map"
Под фреймом должен быть тег `img` с картой на случай, если `js` отвалится

2020-09-21 19:19 UTC, nikkypizza commented on index.html
> +        <li><a class="product" href="product.html">
Для каждой карточки в стайлгайде предусмотрены две кнопки, они должны быть в разметке.
![image](https://user-images.githubusercontent.com/30810655/93810294-17362480-fc57-11ea-8a6f-dbe2970eded8.png)

2020-09-21 19:19 UTC, nikkypizza commented on index.html
> +            title="facebook"><span class="sr-only"></span><svg width="24" height="24" viewBox="0 0 32 32"
Круто, что добавила `title`, это забота о пользователе. Для единообразия давай писать все тайтлы с большой буквы
```suggestion
            title="Facebook"><span class="sr-only"></span><svg width="24" height="24" viewBox="0 0 32 32"
```

2020-09-22 06:59 UTC, nikkypizza commented on index.html
> +      <p><label class="service-button service-button-checked"><input type="radio" name="service"
Лучше так
```suggestion
      <p><label class="service-radio-input"><input type="radio" name="service"
```
Стилизацию будем делать через псевдокласс `:checked` от инпутов

2020-09-23 10:08 UTC, andmitri commented on index.html
> +      <p><label class="service-button service-button-checked"><input type="radio" name="service"
Попробовала сделать с помощью :checked. 
Пробовала разные варианты: 
input[type="radio"]:checked, 
input:checked, 
.service-radio-input:checked.
Ничего из этого не сработало почему-то.

2020-09-23 10:12 UTC, andmitri commented on css/style.css
> +.button{
Добавила text-transform: uppercase.
Если что-то написано капсом, правильнее всегда добавлять это свойство в css или можно просто написать капсом текст в разметке?

2020-09-23 10:12 UTC, andmitri commented on index.html
> +          <div class="label-new">NEW</div>
Удалила блоки label-new.

2020-09-23 10:13 UTC, andmitri commented on index.html
> +  <link href="css/normalize.css" rel="stylesheet">
Подключила библиотеку.

2020-09-23 10:14 UTC, andmitri commented on css/style.css
> +}
Установила плагин бьютифаер =)

2020-09-23 10:14 UTC, andmitri commented on index.html
> +      <iframe class="map"
Добавила тег img.

2020-09-23 10:43 UTC, andmitri commented on index.html
> +            title="facebook"><span class="sr-only"></span><svg width="24" height="24" viewBox="0 0 32 32"
Исправила тайтлы и добавила тайтлы на кнопки.

2020-09-23 11:13 UTC, andmitri commented on index.html
> +        <li><a class="product" href="product.html">
Добавила кнопки и стили к ним.

2020-09-23 11:25 UTC, nikkypizza commented on index.html
> +  <link href="css/normalize.css" rel="stylesheet">
Библиотека эта больше про `js`, тут это просто внешний стилевой файл)

2020-09-23 11:27 UTC, nikkypizza commented on css/style.css
> +.button{
Лучше всегда добавлять `uppercase` из CSS, так интуитивно понятнее

2020-09-23 11:34 UTC, nikkypizza commented on index.html
> +      <p><label class="service-button service-button-checked"><input type="radio" name="service"
Не сработало потому, что мы будем стилизовать не сам `input`, его лейбл.
Для этого нужно:
- Поставить `input` перед `label`, связать их через атрибут `for`.
- Стилизовать через соседствующий селектор: `input[type="radio"]:checked + label`

[Референс по сложным селекторам](https://learn.shayhowe.com/advanced-html-css/complex-selectors/#sibling-selectors)

2020-09-23 11:35 UTC, nikkypizza commented on index.html
> +      <p><label class="service-button service-button-checked"><input type="radio" name="service"
Извини, тут я имел ввиду переименовать не в `service-radio-input`, а в `service-radio-label`. Бес попутал

2020-09-23 11:46 UTC, nikkypizza approved these changes

2020-09-23 11:46 UTC, nikkypizza commented on index.html
> +                    <a>В ЗАКЛАДКИ</a>
Стоит избавиться от `form` и `input type="button"` в карточках товаров. 

- Первое тут ни к чему, потому что как правило клики на кнопку обрабатываются через `js` и форма тут избыточна. Формы как правило нужны для конкретного пользовательского ввода _(поисковая строка, регистрация на сайте, ввод адреса почты и проч)_, избыточно использовать формы для одиночных кнопок
- `input type="button"` используется очень редко, правильнее использовать `button type="button"`
-----
В этой карточке есть две ссылки, но в других карточках их нет, странно

2020-09-23 11:46 UTC, merged

2020-09-24 09:06 UTC, andmitri commented on index.html
> +      <p><label class="service-button service-button-checked"><input type="radio" name="service"
Сделала с помощью input[type="radio"]:checked + label. 9a7e1e1b424454f47c391bb208c079bc513574c4

2020-09-24 09:08 UTC, andmitri commented on index.html
> +                    <a>В ЗАКЛАДКИ</a>
Убрала form, заменила input type на button type. 
Я так понимаю ссылки тут не нужны, я их забыла убрать, убрала. 9a7e1e1b424454f47c391bb208c079bc513574c4